import { Sentence } from './types';

let n = 0;
const s = (
  level: Sentence['level'],
  cat: string,
  de: string,
  tr: string,
  formal: Sentence['formal'],
  tip?: string,
): Sentence => ({ id: `s${++n}`, level, cat, de, tr, formal, tip });

export const SENTENCES: Sentence[] = [
  // ───────── ANREDE / HİTAP ─────────
  s('B1', 'anrede', 'Sehr geehrte Damen und Herren,', 'Saygıdeğer bayanlar ve baylar,', 'resmi', 'Alıcıyı tanımıyorsanız en güvenli resmi hitap budur. Virgülden sonra küçük harfle devam edilir.'),
  s('B1', 'anrede', 'Sehr geehrte Frau Müller,', 'Saygıdeğer Bayan Müller,', 'resmi', 'Soyadı bilinen kadınlara: Sehr geehrte Frau + soyadı.'),
  s('B1', 'anrede', 'Sehr geehrter Herr Schmidt,', 'Saygıdeğer Bay Schmidt,', 'resmi', 'Erkekler için: Sehr geehrter Herr + soyadı. -er takısına dikkat!'),
  s('B1', 'anrede', 'Lieber Thomas,', 'Sevgili Thomas, (erkek arkadaşa)', 'gayriresmi', 'Yakın erkek arkadaşlara: Lieber + isim.'),
  s('B1', 'anrede', 'Liebe Anna,', 'Sevgili Anna, (kadın arkadaşa)', 'gayriresmi', 'Yakın kadın arkadaşlara: Liebe + isim.'),
  s('B2', 'anrede', 'Sehr geehrter Herr Dr. Weber,', 'Saygıdeğer Bay Dr. Weber,', 'resmi', 'Unvan varsa ismin önüne yazılır: Herr Dr., Frau Prof.'),
  s('B2', 'anrede', 'Sehr geehrte Damen und Herren der Stadtverwaltung,', 'Belediye yönetiminin saygıdeğer hanımefendileri ve beyefendileri,', 'resmi', 'Kuruma yazarken daire adı eklemek çok profesyonel durur.'),
  s('B2', 'anrede', 'Liebe Kolleginnen und Kollegen,', 'Sevgili iş arkadaşlarım,', 'nötr', 'İş yeri toplu maillerinde standart ve dostça hitap.'),
  s('B2', 'anrede', 'Hallo Frau Schneider,', 'Merhaba Bayan Schneider,', 'nötr', 'Yarı resmi e-postalarda modern ve yaygın hitap.'),
  s('B2', 'anrede', 'Guten Tag, liebe Familie Becker,', 'İyi günler, sevgili Becker ailesi,', 'gayriresmi', 'Ailelere yazarken çoğul sıcak hitap.'),
  s('C1', 'anrede', 'Sehr verehrte Damen und Herren,', 'Çok saygıdeğer hanımefendiler ve beyefendiler,', 'resmi', 'Festrede / çok üst düzey resmi davet ve kutlama mektuplarında kullanılır.'),
  s('C1', 'anrede', 'Hochverehrter Herr Professor Schneider,', 'Pek muhterem Profesör Schneider,', 'resmi', 'Akademik makama yazarken en üst düzey saygı ifadesi.'),
  s('C1', 'anrede', 'Sehr geehrte Frau Bundesministerin,', 'Saygıdeğer Bayan Federal Bakan,', 'resmi', 'Kamu makamına unvanla hitap; sınavda etkileyici durur.'),
  s('C1', 'anrede', 'Verehrte Gäste, liebe Freunde,', 'Saygıdeğer misafirler, sevgili dostlar,', 'nötr', 'Açılış konuşması / davet mektubu tonunda edebi hitap.'),

  // ───────── EINLEITUNG / GİRİŞ ─────────
  s('B1', 'einleitung', 'Vielen Dank für Ihren Brief vom 12. Mai.', '12 Mayıs tarihli mektubunuz için çok teşekkür ederim.', 'resmi', 'Tarihli teşekkür girişi her resmi mektupta güven verir.'),
  s('B1', 'einleitung', 'Ich habe mich sehr über deine Nachricht gefreut.', 'Mesajına çok sevindim.', 'gayriresmi', 'Arkadaşa yazarken sıcak giriş cümlesi.'),
  s('B1', 'einleitung', 'Ich schreibe Ihnen, weil ich eine Frage habe.', 'Size bir sorum olduğu için yazıyorum.', 'resmi', 'B1 sınavında en pratik giriş kalıbı: Ich schreibe Ihnen, weil ...'),
  s('B1', 'einleitung', 'Wie geht es dir? Mir geht es gut.', 'Nasılsın? Ben iyiyim.', 'gayriresmi', 'Kişisel mektupların klasik açılışı.'),
  s('B1', 'einleitung', 'Ich möchte mich kurz vorstellen: Mein Name ist Elif Yılmaz.', 'Kendimi kısaca tanıtmak istiyorum: Adım Elif Yılmaz.', 'nötr', 'Başvurularda kendini tanıtma kalıbı.'),
  s('B2', 'einleitung', 'Mit großem Interesse habe ich Ihre Anzeige gelesen.', 'İlanınızı büyük bir ilgiyle okudum.', 'resmi', 'Bewerbung (iş başvurusu) mektuplarının yıldız girişi.'),
  s('B2', 'einleitung', 'Bezugnehmend auf unser Telefonat vom Montag, schreibe ich Ihnen heute.', 'Pazartesi günkü telefon görüşmemize istinaden size bugün yazıyorum.', 'resmi', 'Partizipialkonstruktion — B2 seviyesi gösterir.'),
  s('B2', 'einleitung', 'Endlich komme ich dazu, dir ausführlich zu schreiben.', 'Sonunda sana uzun uzun yazmaya fırsat buldum.', 'gayriresmi', 'Samimi gecikmiş cevap girişi.'),
  s('B2', 'einleitung', 'Gestatten Sie mir, dass ich mich vorstelle: Ich bin seit drei Jahren Kunde bei Ihnen.', 'Kendimi tanıtmama izin verin: Üç yıldır müşterinizim.', 'resmi', 'Kibar ve mesafeli resmi tanışma.'),
  s('C1', 'einleitung', 'Anlässlich Ihres Schreibens vom 3. September nehme ich wie folgt Stellung:', '3 Eylül tarihli yazınız vesilesiyle görüşlerimi şu şekilde bildiriyorum:', 'resmi', 'Widerspruch / hukuki cevaplarda üst düzey giriş.'),
  s('C1', 'einleitung', 'Es ist mir ein besonderes Anliegen, Ihnen in dieser Sache zu schreiben.', 'Size bu konuda yazmak benim için özel bir meseledir.', 'resmi', 'C1 dilekçe tonu: vurgulu ve edebi.'),
  s('C1', 'einleitung', 'Nach reiflicher Überlegung habe ich mich entschlossen, Ihnen zu schreiben.', 'Uzun düşünmelerden sonra size yazmaya karar verdim.', 'nötr', 'Ağır konulu mektuplar için olgun giriş.'),
  s('C1', 'einleitung', 'Ihre freundliche Nachricht hat mich außerordentlich gefreut.', 'Nazik mesajınız beni fevkalade sevindirdi.', 'nötr', 'Außerordentlich = B2/C1 kelime, sınavda puan getirir.'),

  // ───────── ANLASS / MEKTUP NEDENİ ─────────
  s('B1', 'anlass', 'Ich schreibe Ihnen wegen meines Termins am Freitag.', 'Size cuma günkü randevum hakkında yazıyorum.', 'resmi', 'wegen + Genitiv. Günlük dilde Dativ de duyulur ama yazıda Genitiv kullanın.'),
  s('B1', 'anlass', 'Der Grund für meinen Brief ist meine neue Adresse.', 'Mektubumun nedeni yeni adresimdir.', 'nötr', 'Der Grund für ... ist ... kalıbı B1 mektuplarında çok işe yarar.'),
  s('B1', 'anlass', 'Leider kann ich nicht zu deiner Party kommen.', 'Maalesef partine gelemem.', 'gayriresmi', 'Absage (iptal) mektuplarının temel cümlesi.'),
  s('B1', 'anlass', 'Ich möchte meinen Aufenthalt um zwei Tage verlängern.', 'Konaklamamı iki gün uzatmak istiyorum.', 'resmi', 'Otel / kurs uzatma talebi için hazır kalıp.'),
  s('B2', 'anlass', 'Anlass meines Schreibens ist die fehlerhafte Rechnung vom 5. Juni.', 'Yazmamın nedeni 5 Haziran tarihli hatalı faturadır.', 'resmi', 'Anlass meines Schreibens ist ... — üst düzey resmi kalıp.'),
  s('B2', 'anlass', 'Ich wende mich an Sie, da mein Antrag bisher unbeantwortet blieb.', 'Başvurum şu ana kadar yanıtsız kaldığı için size başvuruyorum.', 'resmi', 'sich an jemanden wenden = resmi başvurmak. Geçmiş vurgusu için Plusquamperfekt.'),
  s('B2', 'anlass', 'Es geht um den Sprachkurs, der im Oktober beginnt.', 'Söz konusu olan ekimde başlayan dil kursudur.', 'nötr', 'Es geht um ... konuya girmenin en doğal yolu.'),
  s('B2', 'anlass', 'Wie du weißt, ziehe ich nächsten Monat um.', 'Bildiğin gibi, gelecek ay taşınıyorum.', 'gayriresmi', 'Bilgi verme ve konuya bağlama cümlesi.'),
  s('C1', 'anlass', 'Gegen den Bescheid vom 10. August lege ich fristgerecht Widerspruch ein.', '10 Ağustos tarihli karara süresi içinde itiraz ediyorum.', 'resmi', 'Widerspruch dilekçesinin olmazsa olmaz cümlesi. Ezberleyin!'),
  s('C1', 'anlass', 'Hiermit kündige ich meinen Vertrag zum 31. Dezember.', 'İşbu yazıyla sözleşmemi 31 Aralık itibarıyla feshediyorum.', 'resmi', 'Hiermit + kündigen = fesih dilekçesi standardı.'),
  s('C1', 'anlass', 'In oben genannter Angelegenheit bitte ich um eine Überprüfung der Entscheidung.', 'Yukarıda adı geçen konuda kararın gözden geçirilmesini rica ediyorum.', 'resmi', 'Hukuki-idari dilin tipik uzun isim tamlaması.'),
  s('C1', 'anlass', 'Der Zweck dieses Schreibens besteht darin, auf einen Missstand aufmerksam zu machen.', 'Bu yazının amacı bir aksaklığa dikkat çekmektir.', 'resmi', 'besteht darin, ... zu ... — C1 infinitiv kalıbı.'),

  // ───────── BITTE / RİCA ─────────
  s('B1', 'bitte', 'Könnten Sie mir bitte die Unterlagen schicken?', 'Bana belgeleri gönderebilir misiniz lütfen?', 'resmi', 'Konjunktiv II (Könnten Sie ...) = kibar rica. B1 sınavının anahtarı.'),
  s('B1', 'bitte', 'Würdest du mir bitte beim Umzug helfen?', 'Taşınmama yardım eder misin lütfen?', 'gayriresmi', 'Würdest du ...? arkadaşça rica kalıbı.'),
  s('B1', 'bitte', 'Bitte antworten Sie mir so schnell wie möglich.', 'Lütfen bana mümkün olan en kısa sürede cevap verin.', 'resmi', 'so schnell wie möglich = en kısa sürede. Resmi kapanış öncesi klasik.'),
  s('B1', 'bitte', 'Kannst du mich morgen anrufen?', 'Yarın beni arayabilir misin?', 'gayriresmi', 'Günlük kısa rica.'),
  s('B2', 'bitte', 'Ich wäre Ihnen sehr dankbar, wenn Sie mir einen neuen Termin vorschlagen könnten.', 'Bana yeni bir randevu önerebilirseniz çok minnettar olurum.', 'resmi', 'Ich wäre dankbar, wenn ... — B2 kibarlık zirvesi.'),
  s('B2', 'bitte', 'Wären Sie so freundlich, mir die Bestätigung per E-Mail zu senden?', 'Onayı bana e-postayla gönderme inceliğinde bulunur musunuz?', 'resmi', 'Wären Sie so freundlich ...? üst düzey nezaket.'),
  s('B2', 'bitte', 'Es wäre nett, wenn du mir die Fotos schicken könntest.', 'Fotoğrafları gönderebilirsen sevinirim.', 'gayriresmi', 'Es wäre nett, wenn ... samimi ama kibar.'),
  s('B2', 'bitte', 'Ich bitte Sie, meinen Antrag wohlwollend zu prüfen.', 'Başvurumu olumlu değerlendirmenizi rica ediyorum.', 'resmi', 'wohlwollend prüfen = olumlu bakmak. Dilekçe kelimesi.'),
  s('C1', 'bitte', 'Ich ersuche Sie höflich, von weiteren Mahngebühren abzusehen.', 'İlave gecikme ücretlerinden vazgeçmenizi saygıyla talep ediyorum.', 'resmi', 'ersuchen + absehen von — C1 resmi kelimeler.'),
  s('C1', 'bitte', 'Für Ihr Entgegenkommen bedanke ich mich bereits im Voraus.', 'Göstereceğiniz anlayış için şimdiden teşekkür ederim.', 'resmi', 'im Voraus bedanken — resmi mektup kapanış klasiği.'),
  s('C1', 'bitte', 'Ich würde es begrüßen, wenn wir einen persönlichen Gesprächstermin vereinbaren könnten.', 'Şahsen bir görüşme ayarlayabilirsek memnun olurum.', 'resmi', 'Ich würde es begrüßen, wenn ... zarif C1 ricası.'),
  s('C1', 'bitte', 'Darf ich Sie bitten, mir die Vertragsunterlagen zukommen zu lassen?', 'Sözleşme belgelerini bana ulaştırmanızı rica edebilir miyim?', 'resmi', 'zukommen lassen = ulaştırmak. Resmi yazışma fiili.'),

  // ───────── BESCHWERDE / ŞİKAYET ─────────
  s('B1', 'beschwerde', 'Leider ist mein Zimmer sehr laut und schmutzig.', 'Maalesef odam çok gürültülü ve kirli.', 'nötr', 'Otel şikayeti: leider + sıfatlar. Basit ama etkili.'),
  s('B1', 'beschwerde', 'Die Heizung in meinem Zimmer funktioniert nicht.', 'Odamdaki kalorifer çalışmıyor.', 'nötr', 'Somut sorun anlatımı: ... funktioniert nicht.'),
  s('B1', 'beschwerde', 'Ich bin mit dem Essen nicht zufrieden.', 'Yemekten memnun değilim.', 'nötr', 'mit etwas nicht zufrieden sein — şikayet temel kalıbı.'),
  s('B1', 'beschwerde', 'Ich warte schon seit zwei Wochen auf meine Bestellung.', 'Siparişimi iki haftadır bekliyorum.', 'resmi', 'schon seit ... bekliyorum vurgusu sorunu büyütür.'),
  s('B2', 'beschwerde', 'Zu meiner Enttäuschung musste ich feststellen, dass das Gerät defekt ist.', 'Hayal kırıklığıyla cihazın arızalı olduğunu tespit ettim.', 'resmi', 'Zu meiner Enttäuschung musste ich feststellen ... — B2 şikayet girişi.'),
  s('B2', 'beschwerde', 'Trotz mehrmaliger Aufforderung wurde der Schaden bisher nicht behoben.', 'Defalarca talep etmeme rağmen hasar hâlâ giderilmedi.', 'resmi', 'Trotz + Genitiv ve Passiv — sınavda yüksek puan.'),
  s('B2', 'beschwerde', 'Ich fordere Sie auf, den Betrag innerhalb von 14 Tagen zurückzuerstatten.', 'Tutarı 14 gün içinde iade etmenizi talep ediyorum.', 'resmi', 'jemanden auffordern, ... zu ... + süre vermek şikayeti ciddileştirir.'),
  s('B2', 'beschwerde', 'Das entspricht nicht der Beschreibung auf Ihrer Webseite.', 'Bu, web sitenizdeki açıklamaya uymuyor.', 'resmi', 'entsprechen + Dativ. İnternet alışverişi şikayetlerinde birebir.'),
  s('C1', 'beschwerde', 'Mit Bedauern stelle ich fest, dass Ihre Serviceleistung erheblich von der vereinbarten Qualität abweicht.', 'Üzülerek hizmetinizin anlaşılan kaliteden önemli ölçüde saptığını tespit ediyorum.', 'resmi', 'abweichen von + erheblich — C1 şikayet dili.'),
  s('C1', 'beschwerde', 'Sollte keine zufriedenstellende Lösung gefunden werden, sehe ich mich gezwungen, weitere Schritte einzuleiten.', 'Tatmin edici bir çözüm bulunmazsa başka adımlar atmak zorunda kalacağım.', 'resmi', 'sehe mich gezwungen ... kibar ama sert uyarı. Ezberlik!'),
  s('C1', 'beschwerde', 'Ich behalte mir vor, den Vorfall der Verbraucherzentrale zu melden.', 'Olayı tüketici merkezine bildirme hakkımı saklı tutuyorum.', 'resmi', 'sich vorbehalten ... zu ... — hukuki tehdit tonu.'),
  s('C1', 'beschwerde', 'Diese wiederholten Mängel sind für mich nicht länger hinnehmbar.', 'Bu tekrarlanan kusurlar benim için artık kabul edilemez.', 'resmi', 'hinnehmbar = kabul edilebilir. Güçlü C1 sıfatı.'),

  // ───────── MEINUNG / FİKİR ─────────
  s('B1', 'meinung', 'Meiner Meinung nach ist Sport sehr wichtig.', 'Bence spor çok önemlidir.', 'nötr', 'Meiner Meinung nach ... B1 görüş bildirmenin temeli.'),
  s('B1', 'meinung', 'Ich finde, dass das Stadtzentrum zu laut ist.', 'Bence şehir merkezi çok gürültülü.', 'nötr', 'Ich finde, dass ... kişisel görüş kalıbı.'),
  s('B1', 'meinung', 'Ich habe gute Erfahrungen mit diesem Hotel gemacht.', 'Bu otelle ilgili iyi deneyimlerim oldu.', 'nötr', 'Erfahrungen machen mit ... deneyim anlatımı.'),
  s('B1', 'meinung', 'Mein Vorschlag ist, dass wir uns um 18 Uhr treffen.', 'Önerim saat 18.00’de buluşmamız.', 'nötr', 'Mein Vorschlag ist, dass ... öneri sunma kalıbı.'),
  s('B2', 'meinung', 'Ich bin der Ansicht, dass Homeoffice viele Vorteile bietet.', 'Evden çalışmanın birçok avantaj sunduğu görüşündeyim.', 'nötr', 'der Ansicht sein, dass ... B2 görüş kalıbı.'),
  s('B2', 'meinung', 'Einerseits spart man Zeit, andererseits fehlt der persönliche Kontakt.', 'Bir yandan zaman kazanılır, öte yandan kişisel temas eksik kalır.', 'nötr', 'Einerseits ... andererseits ... tartışma yazılarının iskeleti.'),
  s('B2', 'meinung', 'Meines Erachtens sollte die Stadt mehr Radwege bauen.', 'Bana göre şehir daha fazla bisiklet yolu yapmalı.', 'resmi', 'Meines Erachtens = bence (resmi). Leserbrief yıldızı.'),
  s('B2', 'meinung', 'Ich schlage vor, das Treffen auf nächste Woche zu verschieben.', 'Toplantıyı gelecek haftaya ertelemeyi öneriyorum.', 'nötr', 'vorschlagen, ... zu ... öneri fiili.'),
  s('C1', 'meinung', 'Aus meiner Sicht überwiegen die Vorteile bei Weitem die Nachteile.', 'Benim bakış açıma göre avantajlar dezavantajlara açık ara ağır basıyor.', 'nötr', 'überwiegen + bei Weitem — C1 tartışma dili.'),
  s('C1', 'meinung', 'Es lässt sich nicht leugnen, dass der Klimawandel unser Leben verändert.', 'İklim değişikliğinin hayatımızı değiştirdiği inkâr edilemez.', 'nötr', 'Es lässt sich nicht leugnen, dass ... güçlü C1 girişi.'),
  s('C1', 'meinung', 'Ich plädiere dafür, den öffentlichen Nahverkehr stärker zu fördern.', 'Toplu taşımayı daha güçlü desteklemekten yanayım.', 'resmi', 'plädieren für/dafür ... üst düzey savunma fiili.'),
  s('C1', 'meinung', 'Zusammenfassend lässt sich sagen, dass diese Maßnahme dringend erforderlich ist.', 'Özetle bu önlemin acilen gerekli olduğu söylenebilir.', 'nötr', 'Zusammenfassend lässt sich sagen ... sonuç cümlesi.'),

  // ───────── DANK / TEŞEKKÜR & DAVET ─────────
  s('B1', 'dank', 'Vielen Dank für deine Hilfe!', 'Yardımın için çok teşekkürler!', 'gayriresmi', 'En temel teşekkür. Ünlem samimiyet katar.'),
  s('B1', 'dank', 'Ich möchte dich herzlich zu meinem Geburtstag einladen.', 'Seni doğum günüme içtenlikle davet etmek istiyorum.', 'gayriresmi', 'herzlich einladen zu ... davet kalıbı.'),
  s('B1', 'dank', 'Die Party findet am Samstag um 19 Uhr bei mir statt.', 'Parti cumartesi saat 19.00’de bende olacak.', 'gayriresmi', 'stattfinden = gerçekleşmek. Davet detayı için şart.'),
  s('B1', 'dank', 'Vielen Dank für Ihre schnelle Antwort.', 'Hızlı cevabınız için çok teşekkür ederim.', 'resmi', 'Resmi teşekkür standardı.'),
  s('B2', 'dank', 'Ich bedanke mich herzlich für Ihre Unterstützung in dieser Angelegenheit.', 'Bu konudaki desteğiniz için içtenlikle teşekkür ederim.', 'resmi', 'sich bedanken für + in dieser Angelegenheit — resmi teşekkür.'),
  s('B2', 'dank', 'Hiermit lade ich Sie herzlich zu unserer Firmenfeier am 20. Dezember ein.', 'Sizi 20 Aralık’taki şirket kutlamamıza içtenlikle davet ediyorum.', 'resmi', 'Hiermit ... einladen — resmi davet şablonu.'),
  s('B2', 'dank', 'Über eine kurze Rückmeldung würde ich mich sehr freuen.', 'Kısa bir geri dönüş beni çok sevindirir.', 'resmi', 'sich freuen über + Rückmeldung — kibar beklenti.'),
  s('B2', 'dank', 'Herzlichen Glückwunsch zur bestandenen Prüfung!', 'Sınavı geçtiğin için tebrikler!', 'gayriresmi', 'Glückwunsch zu + Dativ. Kutlama mektubu kalıbı.'),
  s('C1', 'dank', 'Für das mir entgegengebrachte Vertrauen möchte ich mich aufrichtig bedanken.', 'Bana duyulan güven için içtenlikle teşekkür etmek istiyorum.', 'resmi', 'entgegengebracht + aufrichtig — C1 şükran dili.'),
  s('C1', 'dank', 'Es wäre mir eine große Ehre, Sie als Ehrengast begrüßen zu dürfen.', 'Sizi onur konuğu olarak ağırlamak benim için büyük bir şeref olur.', 'resmi', 'Ehre + begrüßen dürfen — üst düzey davet.'),
  s('C1', 'dank', 'Ihre großzügige Gastfreundschaft wird mir unvergesslich bleiben.', 'Cömert misafirperverliğiniz benim için unutulmaz kalacak.', 'nötr', 'unvergesslich bleiben — edebi teşekkür kapanışı.'),
  s('C1', 'dank', 'Gestatten Sie mir, Ihnen zu Ihrem Erfolg meine Hochachtung auszusprechen.', 'Başarınızdan dolayı size saygılarımı sunmama izin verin.', 'resmi', 'Hochachtung aussprechen — en resmi tebrik.'),

  // ───────── SCHLUSS / KAPANIŞ ─────────
  s('B1', 'schluss', 'Ich freue mich auf deine Antwort.', 'Cevabını dört gözle bekliyorum.', 'gayriresmi', 'sich freuen auf + Akkusativ. Arkadaş mektubu kapanışı.'),
  s('B1', 'schluss', 'Mit freundlichen Grüßen, Elif', 'Saygılarımla, Elif', 'resmi', 'En yaygın resmi veda. Her resmi mektupta kullanın.'),
  s('B1', 'schluss', 'Liebe Grüße, Mehmet', 'Sevgiler, Mehmet', 'gayriresmi', 'Arkadaşlara standart veda.'),
  s('B1', 'schluss', 'Bis bald und alles Gute!', 'Yakında görüşmek üzere, her şey gönlünce olsun!', 'gayriresmi', 'Sıcak kişisel kapanış.'),
  s('B2', 'schluss', 'Für Rückfragen stehe ich Ihnen gerne zur Verfügung.', 'Sorularınız için memnuniyetle hazırım.', 'resmi', 'zur Verfügung stehen — B2 resmi kapanış yıldızı.'),
  s('B2', 'schluss', 'Ich freue mich darauf, von Ihnen zu hören.', 'Sizden haber almayı dört gözle bekliyorum.', 'resmi', 'sich freuen darauf, ... zu ... resmi beklenti cümlesi.'),
  s('B2', 'schluss', 'Vielen Dank im Voraus für Ihre Bemühungen.', 'Çabalarınız için şimdiden çok teşekkürler.', 'resmi', 'im Voraus — peşin teşekkür, dilekçelerde etkili.'),
  s('B2', 'schluss', 'Melde dich bitte bald!', 'Lütfen yakında haber ver!', 'gayriresmi', 'Samimi cevap beklentisi.'),
  s('C1', 'schluss', 'Hochachtungsvoll', 'Saygılarımla (en resmi)', 'resmi', 'Eskimiş ama hâlâ makamlara yazıda kullanılan en resmi veda.'),
  s('C1', 'schluss', 'In Erwartung Ihrer baldigen Antwort verbleibe ich mit freundlichen Grüßen.', 'Yakın cevabınızı bekleyerek saygılarımla kalıyorum.', 'resmi', 'verbleiben + In Erwartung — klasik C1 dilekçe kapanışı.'),
  s('C1', 'schluss', 'Ich danke Ihnen für Ihre Aufmerksamkeit und verbleibe mit besten Grüßen.', 'İlginiz için teşekkür eder, en iyi dileklerimle kalırım.', 'resmi', 'Uzun resmi mektupların şık finali.'),
  s('C1', 'schluss', 'Mit den besten Wünschen für Sie und Ihre Familie', 'Size ve ailenize en iyi dileklerimle', 'nötr', 'Aileye yönelik zarif kapanış.'),
];
